version: "3.3"
services:

  main-db:
    build:
      context: ./src/database/main
      dockerfile: ./Dockerfile
    ports:
      - "6000:6000"
    expose:
      - "6000"
    command: -p 6000

  user-db:
    build:
      context: ./src/database/user
      dockerfile: ./Dockerfile
    ports:
      - "6001:6001"
    expose:
      - "6001"
    command: -p 6001

  cdn_server:
    build:
      context: .
      dockerfile: ./src/backend/cdn/Dockerfile
    ports:
      - "8080:8080"

  auth_server:
    build:
      context: .
      dockerfile: ./src/backend/auth/Dockerfile
    links:
      - user-db
    depends_on:
      - user-db
    ports:
      - "8082:8082"

  session_server:
    build:
      context: .
      dockerfile: ./src/backend/session/Dockerfile
    links:
      - main-db
    depends_on:
      - main-db
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - session_server
    ports:
      - "4000:4000"

  redis_server:
    image: 'redis'