version: "3.3"
services:

  main-db:
    build:
      context: ./src/database/main
      dockerfile: ./Dockerfile
    image: master.rso:5000/main-db
    ports:
      - "6000:6000"
    expose:
      - "6000"
    command: -p 6000

  user-db:
    build:
      context: ./src/database/user
      dockerfile: ./Dockerfile
    image: master.rso:5000/user-db
    ports:
      - "6001:6001"
    expose:
      - "6001"
    command: -p 6001

  cdn:
    build:
      context: .
      dockerfile: ./src/backend/cdn/Dockerfile
    image: master.rso:5000/cdn
    ports:
      - "8080:8080"
    expose:
      - "8080"

  auth:
    build:
      context: .
      dockerfile: ./src/backend/auth/Dockerfile
    image: master.rso:5000/auth
    links:
      - user-db
    depends_on:
      - user-db
    ports:
      - "8082:8082"
    expose:
      - "8082"

  session:
    build:
      context: .
      dockerfile: ./src/backend/session/Dockerfile
    image: master.rso:5000/session
    links:
      - main-db
    depends_on:
      - main-db
    expose:
      - "8081"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - session
    ports:
      - "4000:4000"

  redis_server:
    image: "redis"
    ports:
      - "6379:6379"