# Dobry tutorial: https://severalnines.com/database-blog/using-kubernetes-deploy-postgresql

{{- range $.Values.psqlServers }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $.Values.appName }}-postgres-{{ .name }}
  labels:
    type: local
    name: {{ $.Values.appName }}-postgres-{{ .name }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/{{ $.Values.appName }}/postgres-{{ .name }}-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.appName }}-postgres-{{ .name }}
  labels:
    name: {{ $.Values.appName }}-postgres-{{ .name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.appName }}-postgres-{{ .name }}
  labels:
    name: {{ $.Values.appName }}-postgres-{{ .name }}
spec:
  selector:
    matchLabels:
      name: {{ $.Values.appName }}-postgres-{{ .name }}
  template:
    metadata:
      labels:
        name: {{ $.Values.appName }}-postgres-{{ .name }}
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: {{ .password }}
            - name: POSTGRES_DB
              value: {{ $.Values.appPrefix }}-{{ .name }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ $.Values.appName }}-postgres-{{ .name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appName }}-postgres-{{ .name }}
  labels:
    name: {{ $.Values.appName }}-postgres-{{ .name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: 5432
  selector:
    name: {{ $.Values.appName }}-postgres-{{ .name }}
  externalIPs:
  {{- range $.Values.workers }}
  - {{ .ip }}
  {{- end }}
---
{{- end }}